{
    'name': "QMS Document Control",
    'version': '19.0.0.2.6',
    'summary': "ISO 9001/IATF 16949/AS 9100D Document Management",
    'author': "Todd Bitner",
    'category': 'Quality',
    'license': 'OPL-1',
    'depends': ['base', 'mail', 'web'], 
    'web_icon': 'qms_document_control,static/description/icon.png',
    'data': [
        'security/qms_groups.xml',
        'security/ir.model.access.csv',
        'data/qms_sequences.xml',
        'data/qms_folder_data.xml',
        'data/mail_template_data.xml',
        'data/mail_server_data.xml',
        'views/qms_document_views.xml',
        'views/qms_menus.xml',
        'reports/qms_reports.xml',
        'reports/qms_report_templates.xml',
    ],
    'post_init_hook': 'post_init_hook',
    'installable': True,
    'application': True,
}